### PR TITLE
[MCC-288947] Big cleanup

### PR DESCRIPTION
**Pull request by masongup-mdsol**
Opening this PR to start testing Travis CI build and fixing unit tests

### CODE REVIEW

**Comment by jcarres-mdsol** [comment]
Are we planning to make a PR to upstream?

**Comment by masongup-mdsol** [comment]
Yes, I'd like to make a PR to upstream once we get the tests passing and everything merged in here

**Comment by jfeltesse-mdsol** [comment]
what's the status of this PR?

edit: I see that PR #14  is more or less based on this one so close or rebase after that one is merged?

**Comment by masongup-mdsol** [comment]
Our team was taken off of the story that was the prompt for this, and from what I have been told, team 4 doesn't have the bandwidth to do a cleanup like this now. I suppose we can just keep it open until somebody is ready to do it.

**Comment by fpcyan** [comment]
Closing since most of this has been implemented now.

**Pull request closed without merging**
